# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: c7a11b742ca67bdde9091763c0aadd0709ff7f64fca6bd1d24f020b4cbbc44ace5b9039772f3ccb67cbb6693077fd480406a58dde7d73a207dca96d7d187d20a

test:
  secret_key_base: 43db9dc3cf07b3cf306006569c9cbcd57d6358895f23478e95a8818fac1be30985c70121e5451fc6bf060428d4ece7ece8bb680fd02c564a7cf1eaa68912dab6

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
